Script started on Fri Apr 22 12:44:29 2022
[1m[7m%[27m[1m[0m                                                                                ]7;file://Nikhils-MacBook-Air.local/Users/nikhil/OneDrive/Documents/Codes/COMP-2710/project5_Patel_nvp0005[0m[27m[24m[Jnikhil@Nikhils-MacBook-Air project5_Patel_nvp0005 % [K[?2004heexit[?2004l

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

Script done on Fri Apr 22 12:45:46 2022
